version: "3.7"

services:
  ts_server:
    build:
      context: ./ts_server
      target: ${TARGET:-dev}
      args:
        - LOG_DIR=${LOG_DIR}
    image: ts_server:latest
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:3000
    volumes:
      - ./ts_server:/srv/app
      - /srv/app/ssl
      - ${SSL_PATH:-./ts_server/ssl}:/srv/app/ssl
      # Please remove # under if you wanna run as server
      #- /srv/app/node_modules
      - /srv/app/dist
    environment:
      - MONGO_URI=${MONGO_URI}
      - LOG_DIR=${LOG_DIR}
    links:
      - mongodb
    depends_on:
      - mongodb
    tty: true
    stdin_open: true
  mongodb:
    image: mongo:7.0.4
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ${DB_PATH}:/data/db